server:
  port: 8001
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1705a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
mybatis:
  # model的包
  type-aliases-package: com.cmsr.sicp.custom.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
      
